# Generated by Django 4.2.5 on 2023-10-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pets.pet'),
        ),
    ]
