# Generated by Django 4.2.5 on 2023-10-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='name',
        ),
    ]
