# Generated by Django 4.2.5 on 2023-10-05 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_remove_trait_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
